/* cours.js — apports théoriques (rappels de cours) affichés au début de chaque TP, sous forme de blocs dépliables */
(function (g) {
  const NS = g.NS = g.NS || {};
  'use strict';
  const C = NS.COURS = {};
  const sub = s => s;
  C.ohm = [
    { t: 'Tension, courant, résistance', h: '<p>La <b>tension</b> U (volt, V) se mesure <b>en parallèle</b> entre deux points. Le <b>courant</b> I (ampère, A) se mesure <b>en série</b> : il faut ouvrir le circuit et y insérer l\'ampèremètre.</p><p><b>Loi d\'Ohm</b> : U = R·I (U en V, R en Ω, I en A). Une résistance de 1 kΩ sous 5 V est traversée par 5 mA.</p><p>Un voltmètre a une résistance interne très grande (≈ 10 MΩ), un ampèremètre très faible : <b>ne jamais brancher un ampèremètre en parallèle sur une source</b> (court-circuit, fusible grillé).</p>' },
    { t: 'L\'alimentation de laboratoire', h: '<p>Elle fournit une tension réglable et une <b>limitation de courant</b> : si la charge réclame plus que la limite, la tension s\'effondre (mode CC, courant constant) pour protéger le montage. Régler d\'abord la tension à vide, puis la limite.</p>' }
  ];
  C.assoc = [{ t: 'Associations de résistances', h: '<p><b>Série</b> : même courant, les tensions s\'ajoutent. R<sub>éq</sub> = R<sub>1</sub> + R<sub>2</sub> + …</p><p><b>Parallèle</b> : même tension, les courants s\'ajoutent. 1/R<sub>éq</sub> = 1/R<sub>1</sub> + 1/R<sub>2</sub> + … ; pour deux résistances R<sub>éq</sub> = R<sub>1</sub>·R<sub>2</sub>/(R<sub>1</sub>+R<sub>2</sub>) (toujours plus petite que la plus petite).</p><p><b>Diviseur de courant</b> : I<sub>1</sub> = I·R<sub>2</sub>/(R<sub>1</sub>+R<sub>2</sub>) — la plus petite résistance prend le plus de courant.</p><p><b>Mesure d\'une résistance</b> : toujours <b>hors tension</b> et composant isolé, sinon l\'ohmmètre mesure tout le réseau.</p>' }];
  C.kirchhoff = [{ t: 'Lois de Kirchhoff', h: '<p><b>Loi des nœuds</b> : la somme des courants qui arrivent à un nœud égale la somme de ceux qui en partent (Σ I<sub>entrants</sub> = Σ I<sub>sortants</sub>).</p><p><b>Loi des mailles</b> : la somme algébrique des tensions le long d\'une maille fermée est nulle. On choisit un sens de parcours ; une tension est comptée + si on traverse le dipôle de − vers +… selon la convention choisie, et on s\'y tient.</p><p>Méthode : orienter les courants, écrire les équations des nœuds et des mailles indépendantes, résoudre, puis <b>vérifier par la mesure</b> (écart attendu &lt; 2–3 %, dû à la tolérance des résistances).</p>' }];
  C.diviseur = [{ t: 'Diviseur de tension', h: '<p>Deux résistances en série sous une tension E : <b>U<sub>s</sub> = E·R<sub>2</sub>/(R<sub>1</sub> + R<sub>2</sub>)</b>, U<sub>s</sub> étant prise aux bornes de R<sub>2</sub>. Valable <b>à vide</b> (aucun courant prélevé).</p><p>Si on branche une charge (ou un voltmètre de résistance interne R<sub>v</sub>), R<sub>2</sub> est remplacée par R<sub>2</sub>//R<sub>v</sub> : la tension mesurée baisse. L\'erreur est faible si R<sub>v</sub> ≫ R<sub>2</sub> (règle : R<sub>v</sub> ≥ 100·R<sub>2</sub>). C\'est l\'<b>erreur de méthode</b> : l\'instrument perturbe ce qu\'il mesure.</p>' }];
  C.puissance = [{ t: 'Puissance et effet Joule', h: '<p>P = U·I = R·I² = U²/R (en watts). Dans une résistance, toute la puissance est transformée en <b>chaleur</b> (effet Joule).</p><p>Une résistance a une <b>puissance maximale</b> (1/4 W, 1/2 W, 1 W…). On dimensionne avec une <b>marge ×2</b> : P<sub>nominale</sub> ≥ 2·P<sub>dissipée</sub>. Au-delà : surchauffe, dérive de valeur puis destruction (visible à la caméra thermique).</p><p>Énergie : W = P·t (joules, ou Wh).</p>' }];
  C.led = [{ t: 'La LED et sa résistance de limitation', h: '<p>Une LED est une diode : elle ne conduit que dans un sens (anode + → cathode −) et à partir d\'une <b>tension de seuil</b> V<sub>F</sub> (≈ 1,8–2 V rouge, ≈ 3 V bleue/blanche). Au-delà, le courant croît très vite : <b>sans résistance, elle est détruite</b>.</p><p>Loi des mailles : E = R·I<sub>F</sub> + V<sub>F</sub> donc <b>R = (E − V<sub>F</sub>)/I<sub>F</sub></b>. Exemple : E = 5 V, V<sub>F</sub> = 2 V, I<sub>F</sub> = 10 mA → R = 300 Ω → on prend la valeur normalisée <b>E12</b> supérieure (330 Ω) pour ne pas dépasser I<sub>F</sub>.</p><p>Série E12 : 10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82 (× 10<sup>n</sup>).</p>' }];
  C.rc = [{ t: 'Circuit RC : charge et décharge', h: '<p>Le condensateur stocke des charges : Q = C·U, et i = C·du/dt. La tension à ses bornes <b>ne peut pas varier instantanément</b>.</p><p><b>Constante de temps</b> τ = R·C. Charge : u<sub>C</sub>(t) = E·(1 − e<sup>−t/τ</sup>) ; décharge : u<sub>C</sub>(t) = E·e<sup>−t/τ</sup>.</p><p>À t = τ : 63 % de la valeur finale (charge) ou 37 % de la valeur initiale (décharge). Le régime est considéré établi après <b>5 τ</b> (99,3 %).</p><p>Sur l\'oscilloscope : repérer 0,63·E et lire le temps correspondant = τ. Ordre de grandeur : 10 kΩ × 100 nF = 1 ms.</p>' }];
  C.signaux = [{ t: 'Signaux périodiques et oscilloscope', h: '<p><b>Période</b> T (s) et <b>fréquence</b> f = 1/T (Hz). Pour un sinus : <b>V<sub>eff</sub> = V<sub>max</sub>/√2</b> (≈ 0,707·V<sub>max</sub>) ; V<sub>pp</sub> = 2·V<sub>max</sub> (sans composante continue). Valeur moyenne d\'un sinus pur : 0 V.</p><p>Le multimètre en V∿ donne la valeur <b>efficace</b>, en V⎓ la valeur <b>moyenne</b>.</p><p>Oscilloscope : la <b>sensibilité verticale</b> (V/div) et la <b>base de temps</b> (s/div) se règlent pour occuper l\'écran ; le <b>déclenchement</b> (trigger, niveau et front) stabilise l\'image. Mesure = nombre de divisions × calibre. Couplage DC : tout le signal ; AC : la composante continue est retirée. La masse de la sonde est <b>reliée à la masse du circuit</b>.</p>' }];
  C.filtre = [{ t: 'Filtre RC passe-bas', h: '<p>Le condensateur laisse mal passer les basses fréquences et court-circuite les hautes : le montage R en série, C en parallèle sur la sortie est un <b>passe-bas</b>.</p><p>Fréquence de coupure : <b>f<sub>c</sub> = 1/(2π·R·C)</b>. Gain : G = U<sub>s</sub>/U<sub>e</sub>. À f<sub>c</sub>, G = 1/√2 ≈ <b>0,707</b>, soit <b>−3 dB</b>, et la sortie est en retard de 45°.</p><p>Gain en décibels : G<sub>dB</sub> = 20·log(U<sub>s</sub>/U<sub>e</sub>). Au-delà de f<sub>c</sub>, le gain décroît de <b>−20 dB par décade</b>.</p><p>Exemple : R = 1,6 kΩ, C = 100 nF → f<sub>c</sub> ≈ 1 kHz.</p>' }];
  C.transfo = [{ t: 'Le transformateur', h: '<p>Deux enroulements (primaire / secondaire) couplés par un noyau magnétique : il ne fonctionne qu\'en <b>alternatif</b> et <b>isole galvaniquement</b> le secondaire du secteur.</p><p>Rapport de transformation : <b>m = U<sub>2</sub>/U<sub>1</sub> = N<sub>2</sub>/N<sub>1</sub></b>. Un 230 V / 12 V a m ≈ 0,052. Les valeurs sont des tensions <b>efficaces</b> : la tension crête secondaire est 12·√2 ≈ 17 V.</p><p>À vide la tension est un peu plus haute que la valeur nominale ; en charge elle baisse (résistance des enroulements). Puissance apparente S = U·I en <b>VA</b>.</p><p><b>Sécurité</b> : le primaire est au potentiel du secteur (230 V) — on ne mesure jamais à main nue.</p>' }];
  C.redress = [{ t: 'Redressement', h: '<p>Une diode idéale conduit si V<sub>A</sub> &gt; V<sub>K</sub> + V<sub>seuil</sub> (≈ 0,6–0,7 V pour le silicium), sinon elle est bloquée.</p><p><b>Simple alternance</b> : une diode, on garde une alternance sur deux. V<sub>moy</sub> ≈ V<sub>max</sub>/π.</p><p><b>Double alternance</b> (pont de 4 diodes) : deux diodes conduisent à chaque alternance (on perd 2 × V<sub>seuil</sub>) ; V<sub>moy</sub> ≈ 2·V<sub>max</sub>/π ≈ 0,64·V<sub>max</sub>, fréquence d\'ondulation = <b>2 × 50 Hz = 100 Hz</b>.</p><p>La tension reste « pulsée » : on la filtre ensuite avec un condensateur.</p>' }];
  C.filtrage = [{ t: 'Filtrage par condensateur', h: '<p>Le condensateur se charge au sommet de chaque arche puis se décharge dans la charge : la tension devient presque continue avec une <b>ondulation</b> ΔV.</p><p>Pour un redressement double alternance : <b>ΔV ≈ I/(2·f·C)</b> (f = 50 Hz) ; simple alternance : ΔV ≈ I/(f·C). Plus C et plus f sont grands, plus l\'ondulation est faible.</p><p>Dimensionnement : C ≥ I/(2·f·ΔV). Ex. 110 mA, ΔV = 1 V : C ≥ 1,1 mF → on prend 2200 µF. Choisir une <b>tension de service</b> supérieure à V<sub>max</sub> (marge ≥ 30 %), attention à la polarité des chimiques.</p><p>Un condensateur vieilli (séché) a une capacité plus faible et une résistance série élevée : l\'ondulation augmente.</p>' }];
  C.regul = [{ t: 'Régulation linéaire (78xx)', h: '<p>Le régulateur <b>7805</b> fournit 5 V stables tant que U<sub>e</sub> ≥ U<sub>s</sub> + <b>dropout</b> (≈ 2 V) : il faut donc au moins ≈ 7 V en entrée, et pas plus de 35 V.</p><p>Il se comporte comme une résistance variable en série avec la charge : la puissance perdue est <b>P = (U<sub>e</sub> − U<sub>s</sub>)·I</b>, transformée en chaleur (rendement η = U<sub>s</sub>/U<sub>e</sub>). Si P est grande → dissipateur thermique.</p><p>Condensateurs de découplage (≈ 330 nF en entrée, 100 nF en sortie) pour la stabilité. Le régulateur a une limitation de courant (≈ 1 A) et une protection thermique.</p>' }];
  C.test = [{ t: 'Tester un composant hors tension', h: '<p>Toujours <b>hors tension</b> et, si possible, composant déconnecté d\'au moins une borne (sinon on mesure le réseau).</p><p><b>Ohmmètre</b> : le multimètre injecte un petit courant et mesure la tension. Résistance : comparer à la valeur nominale ± tolérance (5 % : bandes or). Coupée → « OL » ; en court-circuit → ≈ 0 Ω.</p><p><b>Test diode</b> : sens passant → affiche V<sub>seuil</sub> (≈ 0,5–0,7 V) ; sens bloquant → « OL ». Les deux sens bas = diode en court-circuit ; les deux « OL » = coupée.</p><p><b>Continuité</b> : bip si R &lt; quelques dizaines d\'Ω (fusible, câble, piste).</p><p>Astuce : l\'outil <b>🔴 Pointes</b> permet de poser les pointes d\'un clic sur les bornes, comme en vrai.</p>' }];
  C.zener = [{ t: 'La diode Zener', h: '<p>Polarisée en <b>inverse</b>, une Zener conduit à partir de sa tension V<sub>Z</sub> (claquage non destructif) et maintient alors ≈ V<sub>Z</sub> à ses bornes, malgré les variations de courant. En direct, elle se comporte comme une diode normale.</p><p>Stabilisation : résistance série R<sub>S</sub> + Zener en parallèle sur la charge. <b>R<sub>S</sub> = (E − V<sub>Z</sub>)/(I<sub>Z</sub> + I<sub>charge</sub>)</b>.</p><p>Il faut I<sub>Z min</sub> pour rester dans la zone de Zener ; la Zener dissipe P<sub>Z</sub> = V<sub>Z</sub>·I<sub>Z</sub> (≤ P<sub>max</sub>, 0,5 W ou 1,3 W). Au pire : charge débranchée, tout le courant passe dans la Zener.</p>' }];
  C.transistor = [{ t: 'Transistor bipolaire en commutation', h: '<p>NPN : le petit courant de <b>base</b> I<sub>B</sub> commande le courant de <b>collecteur</b> I<sub>C</sub> : <b>I<sub>C</sub> = β·I<sub>B</sub></b> (β ≈ 100–300) tant qu\'il est en régime linéaire. V<sub>BE</sub> ≈ 0,7 V quand la base conduit.</p><p><b>Bloqué</b> : I<sub>B</sub> = 0 → I<sub>C</sub> ≈ 0, V<sub>CE</sub> ≈ V<sub>cc</sub> (interrupteur ouvert).<br><b>Saturé</b> : I<sub>B</sub> est assez grand pour que I<sub>C</sub> = (V<sub>cc</sub> − V<sub>CEsat</sub>)/R<sub>C</sub>, V<sub>CE</sub> ≈ 0,1–0,2 V (interrupteur fermé).</p><p>Pour saturer : <b>I<sub>B</sub> ≥ I<sub>C</sub>/β</b>, avec une marge (×2 à ×5). R<sub>B</sub> = (V<sub>commande</sub> − 0,7)/I<sub>B</sub>.</p>' }];
  C.relais = [{ t: 'Relais et charges inductives', h: '<p>Un <b>relais</b> commande un circuit de puissance (contacts COM / NO normalement ouvert / NC normalement fermé) à partir d\'un petit courant dans sa <b>bobine</b>, avec isolation galvanique.</p><p>Une bobine s\'oppose aux variations de courant : <b>u = −L·di/dt</b>. Quand le transistor coupe brutalement le courant, une <b>surtension</b> de plusieurs dizaines de volts apparaît, capable de détruire le transistor (claquage, avalanche).</p><p>Solution : <b>diode de roue libre</b> en inverse aux bornes de la bobine : elle offre au courant un chemin pour s\'éteindre, la tension est limitée à ≈ V<sub>cc</sub> + 0,7 V. Cathode côté +.</p>' }];
  C.inverseur = [{ t: 'L\'AOP en amplificateur inverseur', h: '<p>Un amplificateur opérationnel (AOP) amplifie la différence ε = V<sub>+</sub> − V<sub>−</sub>. Il est alimenté en <b>±12 V</b> (alimentation symétrique) et sa sortie ne peut pas dépasser ≈ les tensions d\'alimentation : c\'est la <b>saturation</b>.</p><p>Avec une <b>contre-réaction</b> (R<sub>f</sub> de la sortie vers l\'entrée −), l\'AOP est en régime linéaire : ε ≈ 0 et V<sub>−</sub> ≈ V<sub>+</sub> = 0 V (masse virtuelle). Le courant d\'entrée est nul.</p><p><b>Gain G = V<sub>s</sub>/V<sub>e</sub> = − R<sub>f</sub>/R<sub>1</sub></b> (signe − : sortie en opposition de phase). Dès que |G·V<sub>e</sub>| dépasse la tension de saturation, la sortie est écrêtée.</p>' }];
  C.cre = [{ t: 'Comparateur et capteur LDR', h: '<p>La <b>LDR</b> (photorésistance) a une résistance qui <b>diminue quand l\'éclairement augmente</b> (quelques centaines d\'Ω en plein jour, plusieurs MΩ dans le noir).</p><p>Placée dans un <b>pont diviseur</b>, elle donne une tension V<sub>mesure</sub> image de la lumière. Un AOP <b>sans contre-réaction</b> (comparateur) compare V<sub>+</sub> et V<sub>−</sub> : si V<sub>+</sub> &gt; V<sub>−</sub> la sortie vaut +V<sub>sat</sub>, sinon −V<sub>sat</sub>. Un potentiomètre règle le <b>seuil</b> de basculement.</p><p>La sortie du comparateur commande ensuite un transistor et un relais ou une LED (lampe qui s\'allume à la tombée de la nuit).</p>' }];
  const METH = { t: 'Méthode de dépannage', h: '<ol><li><b>Constater</b> le symptôme (que fait le système, que devrait-il faire ?) ;</li><li><b>Hypothèses</b> : quels blocs de la chaîne fonctionnelle peuvent l\'expliquer ?</li><li><b>Mesurer sous tension</b> en remontant de la sortie vers l\'entrée : on cherche le premier point où la tension est anormale (dichotomie) ;</li><li><b>Localiser</b> le bloc, puis, <b>hors tension</b>, tester les composants (ohmmètre, diode, continuité) ;</li><li><b>Chercher la cause</b> avant de remplacer (un fusible qui fond est le symptôme d\'un court-circuit) ;</li><li><b>Réparer</b> (composant identique) et <b>contrôler</b> le fonctionnement complet.</li></ol><p><b>Sécurité</b> : couper et décharger les condensateurs avant d\'intervenir ; ne jamais court-circuiter ni mettre de fusible plus fort.</p>' };
  C.dep1 = [METH, { t: 'Rappels : la chaîne d\'alimentation 5 V', h: '<p>Secteur 230 V → <b>fusible</b> (protège du court-circuit, I²t) → <b>transformateur</b> (230 V → 12 V~, isolation) → <b>pont de diodes</b> (redressement) → <b>condensateur de filtrage</b> (≈ 16–17 V avec ondulation) → <b>régulateur 7805</b> (5 V) → charge.</p><p>Valeurs attendues : secondaire ≈ 12 V<sub>eff</sub> ; après filtrage ≈ 15–16 V ; sortie 5 V. Ondulation à 100 Hz. Les écarts guident la localisation : pas de tension du tout → fusible, transformateur ; tension filtrée OK mais pas de 5 V → régulateur ; forte ondulation → diode ouverte ou C séché.</p><p>Un composant en court-circuit peut en détruire d\'autres (panne <b>en cascade</b>) : toujours chercher la cause avant de remettre sous tension. La <b>caméra thermique</b> repère les composants anormalement chauds.</p>' }];
  C.dep2 = [METH, { t: 'Rappels : le transistor en commutation', h: '<p>Chaîne : SW1 → R<sub>B</sub> → base ; R<sub>C</sub> et LED en série avec collecteur-émetteur. Fonctionnement normal fermé : V<sub>BE</sub> ≈ 0,7 V, V<sub>CE</sub> ≈ 0,1 V (saturé), LED allumée. Ouvert : V<sub>BE</sub> ≈ 0, V<sub>CE</sub> ≈ V<sub>cc</sub>.</p><p>Diagnostic : V<sub>BE</sub> = 0 alors que SW1 est fermé → circuit de commande coupé (R<sub>B</sub>, fil, interrupteur). V<sub>BE</sub> ≈ 0,7 V mais V<sub>CE</sub> ≈ V<sub>cc</sub> → transistor coupé entre C et E. V<sub>CE</sub> ≈ 0 LED éteinte alors que SW1 ouvert → C-E en court-circuit.</p>' }];
  C.dep3 = [METH, { t: 'Rappels : l\'AOP inverseur et son alimentation', h: '<p>Un AOP a besoin de <b>V+ et V− (±12 V)</b> sur ses broches d\'alimentation : <b>vérifier l\'alimentation avant tout</b>. Sans une des deux, la sortie reste à 0 V ou bloquée.</p><p>Gain attendu G = −R<sub>f</sub>/R<sub>1</sub>. Sortie écrêtée à ≈ ±V<sub>sat</sub> quelle que soit l\'entrée → boucle de contre-réaction ouverte (R<sub>f</sub> coupée). Sortie à 0 V avec une entrée présente → R<sub>1</sub> coupée, AOP HS ou alimentation absente.</p><p>On compare à l\'oscilloscope entrée (CH1) et sortie (CH2).</p>' }];

  C.portes = [{ t: 'Portes logiques et niveaux', h: '<p>Une porte combine des entrées binaires (0 / 1) : <b>ET</b> (1 si A et B), <b>OU</b>, <b>NON</b>, <b>NON-ET</b> (NAND), <b>NON-OU</b> (NOR), <b>OU exclusif</b> (XOR : 1 si A ≠ B). Sa <b>table de vérité</b> donne la sortie pour chaque combinaison d\'entrées.</p><p><b>Alimentation</b> : un circuit intégré se branche sur VCC et GND ; sans alimentation la sortie n\'a aucun sens. <b>CMOS (74HC)</b> : niveaux ≈ 0 V et Vcc, entrées à très haute impédance, entrée libre = indéterminée. <b>TTL (74LS)</b> : sortie haute ≈ 3,4 V ; une entrée au niveau bas <i>débite ≈ 0,4 mA</i> (le pull-down doit être faible : 470 Ω) ; une entrée libre est lue « 1 ». Toujours relier les entrées par une <b>résistance de rappel</b>.</p>' }];
  C.ne555 = [{ t: 'Le NE555 en astable', h: '<p>Le 555 contient un diviseur 3 × 5 kΩ (d\'où son nom), deux comparateurs (seuils <b>Vcc/3</b> sur TRIG et <b>2·Vcc/3</b> sur THR), une bascule SR et un transistor de décharge (DIS). En astable, C se charge par R1 + R2 de Vcc/3 à 2·Vcc/3, puis se décharge par R2 : <b>t<sub>H</sub> = 0,69·(R1 + R2)·C</b>, <b>t<sub>L</sub> = 0,69·R2·C</b>, <b>f = 1,44 / ((R1 + 2·R2)·C)</b>. Rapport cyclique α = (R1 + R2)/(R1 + 2·R2) &gt; 50 %.</p><p>Le NE555 (bipolaire) supporte 200 mA en sortie ; le TLC555 (CMOS) consomme très peu mais ne fournit que 10 mA.</p>' }];
  C.opto = [{ t: 'Optocoupleur et isolation galvanique', h: '<p>Une LED infrarouge éclaire un phototransistor : le signal passe par la <b>lumière</b>, sans liaison électrique (tenue en tension typ. 5 kV). On protège ainsi un circuit logique d\'un circuit de puissance ou d\'un bus parasité.</p><p><b>CTR</b> = I<sub>C</sub>/I<sub>F</sub> (PC817 ≈ 100 %, 4N25 ≈ 20-30 %). Pour <b>saturer</b> la sortie : I<sub>C,sat</sub> = (V<sub>alim</sub> − 0,2)/R<sub>C</sub>, puis I<sub>F</sub> ≥ 2·I<sub>C,sat</sub>/CTR (marge, car le CTR varie beaucoup) ; R<sub>A</sub> = (V<sub>commande</sub> − V<sub>F</sub>)/I<sub>F</sub>.</p>' }];
  C.mosfet = [{ t: 'Le MOSFET en commutation', h: '<p>Le MOSFET est commandé par la <b>tension V<sub>GS</sub></b> (grille isolée : courant de grille nul en continu). Bloqué si V<sub>GS</sub> &lt; V<sub>GS(th)</sub> ; saturé (R<sub>DS(on)</sub> de quelques mΩ à quelques dizaines de mΩ) si V<sub>GS</sub> est nettement supérieur au seuil. Un MOSFET standard (IRF540N) veut ≈ 10 V ; un <b>logic-level</b> (IRLZ44N) conduit à 4,5 V, voire 3,3 V.</p><p>Pertes en conduction : P = R<sub>DS(on)</sub>·I<sub>D</sub>². Mal commandé, le MOSFET reste en zone linéaire (V<sub>DS</sub> élevée) : il chauffe et peut être détruit. Vérifier aussi I<sub>D,max</sub> (2N7000 : 200 mA).</p>' }];
  C.dep_log = [METH, { t: 'Rappels : dépanner une chaîne logique', h: '<p>On suit le signal d\'étage en étage et on compare le niveau mesuré à la <b>table de vérité</b>. Sortie qui ne change jamais = sortie bloquée (circuit défectueux ou alimentation absente). <b>Mesurer VCC sur la broche du circuit</b>. Sortie correcte mais récepteur éteint → charge ou résistance coupée.</p>' }];
  C.uart = [{ t: 'La trame UART et le RS-232', h: '<p>Liaison <b>asynchrone</b> : pas d\'horloge, les deux extrémités s\'accordent sur le <b>débit</b> (bauds : 9600, 19200, 115200…). Trame : repos à 1 → <b>start</b> (0) → 7 ou 8 bits de données, <b>bit de poids faible d\'abord</b> → parité éventuelle (paire : le nombre total de 1 est pair) → 1 ou 2 <b>stops</b> (1). Durée d\'un bit T = 1/débit ; « 8N1 » = 8 données, pas de parité, 1 stop (10 bits par octet).</p><p>Niveaux TTL (0 / 3,3 ou 5 V) pour les microcontrôleurs ; <b>RS-232</b> : ±3 à ±15 V (typ. ±12 V), <b>logique inversée</b> (1 = négatif). Messages en ASCII : 0x41 = « A », 0x0D = retour chariot, 0x0A = saut de ligne.</p><p>À l\'analyseur logique : mesurer le plus petit créneau pour trouver le débit, essayer les formats jusqu\'à ne plus avoir d\'erreur de parité ou de stop.</p>' }];
  C.modbus = [{ t: 'Modbus RTU sur RS-485', h: '<p><b>RS-485</b> : liaison <b>différentielle</b> (fils A et B), niveau = A − B (&gt; +200 mV ou &lt; −200 mV) : immunité aux parasites, jusqu\'à 1200 m et 32 nœuds, half-duplex. <b>Modbus RTU</b> : maître/esclaves ; trame = <b>adresse</b> (1 à 247) · <b>fonction</b> · données · <b>CRC16</b> (2 octets, poids faible d\'abord). Les trames sont séparées par un silence ≥ 3,5 caractères.</p><p>Fonction 03 : lire des registres (adresse de début + nombre) ; 06 : écrire un registre ; réponse d\'<b>exception</b> : fonction + 0x80 puis code (01 fonction illégale, 02 adresse illégale, 03 valeur illégale). Un CRC faux = trame altérée, ignorée par le récepteur.</p>' }];
  C.i2c = [{ t: 'Le bus I²C', h: '<p>Deux fils : <b>SCL</b> (horloge, fournie par le maître) et <b>SDA</b> (données bidirectionnelles), tous deux à <b>drain ouvert</b> avec <b>résistances de rappel</b> (typ. 4,7 kΩ au +3,3 V). <b>START</b> : SDA↓ pendant SCL = 1 ; <b>STOP</b> : SDA↑ pendant SCL = 1 ; sinon SDA change quand SCL = 0. Après START : 7 bits d\'<b>adresse</b> (MSB d\'abord) + bit <b>R/W</b>, puis un bit <b>ACK</b> (SDA tiré à 0 par l\'esclave) ; chaque octet est acquitté. Absence de réponse = <b>NACK</b>.</p><p>Vitesses : 100 kHz (standard), 400 kHz (rapide). Exemples : 0x48 capteur de température, 0x68 RTC, 0x3C afficheur OLED.</p>' }];
  C.spi = [{ t: 'Le bus SPI', h: '<p>Quatre fils : <b>SCK</b> (horloge), <b>MOSI</b> (maître → esclave), <b>MISO</b> (esclave → maître), <b>CS</b> (sélection, actif à 0). Transmission <b>synchrone, full-duplex</b>, MSB en premier. Quatre modes selon <b>CPOL</b> (niveau de repos de SCK) et <b>CPHA</b> (échantillonnage au 1<sup>er</sup> ou 2<sup>e</sup> front) : mode 0 (0,0), 1 (0,1), 2 (1,0), 3 (1,1). Maître et esclave doivent utiliser le même mode, sinon les bits sont décalés. Plus rapide que l\'I²C (MHz) mais un CS par esclave.</p>' }];
  C.bascule = [{ t: 'La bascule D', h: '<p>Mémoire d\'un bit : <b>Q recopie D au front montant de CK</b>, puis garde cette valeur. Entrées asynchrones <b>S̅</b> (set, Q = 1) et <b>R̅</b> (reset, Q = 0) <b>actives à l\'état bas</b> et prioritaires : à relier au +5 V quand on ne s\'en sert pas. Câblée avec <b>D = Q̅</b>, elle bascule à chaque front d\'horloge : <b>diviseur de fréquence par 2</b>, de rapport cyclique 50 %.</p>' }];
  C.compteur = [{ t: 'Compteurs binaires', h: '<p>Un compteur 4 bits enchaîne quatre bascules : l\'état (Q3 Q2 Q1 Q0) augmente de 1 à chaque front d\'horloge, de 0 à 15 puis retour à 0 (<b>modulo 16</b>). Chaque sortie divise par 2 la précédente : f(Q<sub>n</sub>) = f<sub>CK</sub>/2<sup>n+1</sup>. <b>MR</b> force 0000 tant qu\'il vaut 1 (asynchrone). Poids : Q0 = 1, Q1 = 2, Q2 = 4, Q3 = 8.</p>' }];
  C.modulo = [{ t: 'Compteur modulo N', h: '<p>Pour compter de 0 à N − 1 : on <b>décode l\'état N</b> (porte ET sur ses bits à 1) et on envoie ce signal sur la remise à zéro. N = 10 → Q3·Q1 ; N = 6 → Q2·Q1. L\'état N n\'existe que quelques nanosecondes. Même principe pour les diviseurs par N, les compteurs BCD et les séquenceurs.</p>' }];
  C.la_intro = [{ t: 'L\'analyseur logique', h: '<p>Il observe plusieurs signaux <b>numériques</b> à la fois (jusqu\'à 8 voies) : chaque tension est comparée à un <b>seuil</b> et affichée en 0 / 1 dans le temps (chronogramme). Réglages : <b>base de temps</b> (durée par division), <b>déclenchement</b> (voie + front qui démarre l\'affichage), <b>seuil</b>, <b>RUN/STOP</b> (figer), <b>curseurs</b> (mesure de durées). Il sait aussi <b>décoder</b> des protocoles (UART, Modbus, I²C, SPI). Comparé à l\'oscilloscope : plus de voies et décodage, mais pas de niveaux analogiques précis.</p>' }];
  C.osc_lect = [{ t: 'Lire un signal à l\'oscilloscope', h: '<p><b>Base de temps</b> (s/div) : T = nb de divisions horizontales × s/div, puis f = 1/T. <b>Sensibilité</b> (V/div) : U = nb de divisions verticales × V/div. Réglage idéal : 2 à 10 périodes et un signal de 4 à 6 divisions de haut. <b>Déclenchement</b> : démarre le balayage sur un front pour une image stable ; <b>Auto</b> propose un réglage.</p><p>Grandeurs : U<sub>max</sub>, U<sub>min</sub>, <b>U<sub>pp</sub> = U<sub>max</sub> − U<sub>min</sub></b>, amplitude (crête) = U<sub>pp</sub>/2, <b>valeur moyenne</b> (composante continue, V⎓), <b>valeur efficace</b> de la partie alternative (V∿) : sinus U<sub>max</sub>/√2, triangle U<sub>max</sub>/√3, carré symétrique U<sub>max</sub>.</p>' }];
  C.osc_carre = [{ t: 'Signal rectangulaire et rapport cyclique', h: '<p>Un signal rectangulaire alterne un niveau haut (durée t<sub>H</sub>) et un niveau bas. <b>Rapport cyclique α = t<sub>H</sub>/T</b>. Valeur moyenne : <b>U<sub>moy</sub> = α·U<sub>haut</sub> + (1 − α)·U<sub>bas</sub></b>. La <b>MLI (PWM)</b> règle la puissance moyenne d\'une LED ou d\'un moteur en variant α à fréquence fixe. Les signaux logiques 0 / 3,3 V ou 0 / 5 V sont rectangulaires.</p>' }];
  C.osc_phi = [{ t: 'Gain et déphasage', h: '<p>Deux voies observent entrée et sortie : <b>gain G = U<sub>s</sub>/U<sub>e</sub></b> (amplitudes). Le <b>retard</b> Δt entre deux passages par zéro donne le <b>déphasage φ = 360° × Δt/T</b> (sortie en retard : φ négatif par convention). Filtre RC passe-bas : G = 1/√(1 + (f/f<sub>c</sub>)²), φ = −arctan(f/f<sub>c</sub>), f<sub>c</sub> = 1/(2πRC) ; à f<sub>c</sub> : G = 0,707 (−3 dB), φ = −45°.</p>' }];
  C.osc_ac = [{ t: 'Couplage DC / AC', h: '<p><b>DC</b> : la voie affiche tout le signal (continu + alternatif). <b>AC</b> : un condensateur en série bloque la composante continue (filtre passe-haut, ~10 Hz) : on voit seulement la partie alternative, ce qui permet d\'augmenter la sensibilité pour mesurer une <b>ondulation</b> de quelques dizaines de mV sur une tension de 12 V. <b>Taux d\'ondulation</b> = U<sub>pp</sub>/U<sub>moy</sub>. En AC les composantes très lentes sont atténuées : on ne mesure pas la valeur moyenne.</p>' }];
  NS.coursFor = id => C[id] || [];
})(typeof window !== 'undefined' ? window : globalThis);
