/* cours.js — apports théoriques (rappels de cours) affichés au début de chaque TP, sous forme de blocs dépliables */
(function (g) {
  const NS = g.NS = g.NS || {};
  'use strict';
  const C = NS.COURS = {};
  const sub = s => s;
  C.ohm = [
    { t: 'Tension, courant, résistance', h: '<p>La <b>tension</b> U (volt, V) se mesure <b>en parallèle</b> entre deux points. Le <b>courant</b> I (ampère, A) se mesure <b>en série</b> : il faut ouvrir le circuit et y insérer l\'ampèremètre.</p><p><b>Loi d\'Ohm</b> : U = R·I (U en V, R en Ω, I en A). Une résistance de 1 kΩ sous 5 V est traversée par 5 mA.</p><p>Un voltmètre a une résistance interne très grande (≈ 10 MΩ), un ampèremètre très faible : <b>ne jamais brancher un ampèremètre en parallèle sur une source</b> (court-circuit, fusible grillé).</p>' },
    { t: 'L\'alimentation de laboratoire', h: '<p>Elle fournit une tension réglable et une <b>limitation de courant</b> : si la charge réclame plus que la limite, la tension s\'effondre (mode CC, courant constant) pour protéger le montage. Régler d\'abord la tension à vide, puis la limite.</p>' }
  ];
  C.assoc = [{ t: 'Associations de résistances', h: '<p><b>Série</b> : même courant, les tensions s\'ajoutent. R<sub>éq</sub> = R<sub>1</sub> + R<sub>2</sub> + …</p><p><b>Parallèle</b> : même tension, les courants s\'ajoutent. 1/R<sub>éq</sub> = 1/R<sub>1</sub> + 1/R<sub>2</sub> + … ; pour deux résistances R<sub>éq</sub> = R<sub>1</sub>·R<sub>2</sub>/(R<sub>1</sub>+R<sub>2</sub>) (toujours plus petite que la plus petite).</p><p><b>Diviseur de courant</b> : I<sub>1</sub> = I·R<sub>2</sub>/(R<sub>1</sub>+R<sub>2</sub>) — la plus petite résistance prend le plus de courant.</p><p><b>Mesure d\'une résistance</b> : toujours <b>hors tension</b> et composant isolé, sinon l\'ohmmètre mesure tout le réseau.</p>' }];
  C.kirchhoff = [{ t: 'Lois de Kirchhoff', h: '<p><b>Loi des nœuds</b> : la somme des courants qui arrivent à un nœud égale la somme de ceux qui en partent (Σ I<sub>entrants</sub> = Σ I<sub>sortants</sub>).</p><p><b>Loi des mailles</b> : la somme algébrique des tensions le long d\'une maille fermée est nulle. On choisit un sens de parcours ; une tension est comptée + si on traverse le dipôle de − vers +… selon la convention choisie, et on s\'y tient.</p><p>Méthode : orienter les courants, écrire les équations des nœuds et des mailles indépendantes, résoudre, puis <b>vérifier par la mesure</b> (écart attendu &lt; 2–3 %, dû à la tolérance des résistances).</p>' }];
  C.diviseur = [{ t: 'Diviseur de tension', h: '<p>Deux résistances en série sous une tension E : <b>U<sub>s</sub> = E·R<sub>2</sub>/(R<sub>1</sub> + R<sub>2</sub>)</b>, U<sub>s</sub> étant prise aux bornes de R<sub>2</sub>. Valable <b>à vide</b> (aucun courant prélevé).</p><p>Si on branche une charge (ou un voltmètre de résistance interne R<sub>v</sub>), R<sub>2</sub> est remplacée par R<sub>2</sub>//R<sub>v</sub> : la tension mesurée baisse. L\'erreur est faible si R<sub>v</sub> ≫ R<sub>2</sub> (règle : R<sub>v</sub> ≥ 100·R<sub>2</sub>). C\'est l\'<b>erreur de méthode</b> : l\'instrument perturbe ce qu\'il mesure.</p>' }];
  C.puissance = [{ t: 'Puissance et effet Joule', h: '<p>P = U·I = R·I² = U²/R (en watts). Dans une résistance, toute la puissance est transformée en <b>chaleur</b> (effet Joule).</p><p>Une résistance a une <b>puissance maximale</b> (1/4 W, 1/2 W, 1 W…). On dimensionne avec une <b>marge ×2</b> : P<sub>nominale</sub> ≥ 2·P<sub>dissipée</sub>. Au-delà : surchauffe, dérive de valeur puis destruction (visible à la caméra thermique).</p><p>Énergie : W = P·t (joules, ou Wh).</p>' }];
  C.led = [{ t: 'La LED et sa résistance de limitation', h: '<p>Une LED est une diode : elle ne conduit que dans un sens (anode + → cathode −) et à partir d\'une <b>tension de seuil</b> V<sub>F</sub> (≈ 1,8–2 V rouge, ≈ 3 V bleue/blanche). Au-delà, le courant croît très vite : <b>sans résistance, elle est détruite</b>.</p><p>Loi des mailles : E = R·I<sub>F</sub> + V<sub>F</sub> donc <b>R = (E − V<sub>F</sub>)/I<sub>F</sub></b>. Exemple : E = 5 V, V<sub>F</sub> = 2 V, I<sub>F</sub> = 10 mA → R = 300 Ω → on prend la valeur normalisée <b>E12</b> supérieure (330 Ω) pour ne pas dépasser I<sub>F</sub>.</p><p>Série E12 : 10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82 (× 10<sup>n</sup>).</p>' }];
  C.rc = [{ t: 'Circuit RC : charge et décharge', h: '<p>Le condensateur stocke des charges : Q = C·U, et i = C·du/dt. La tension à ses bornes <b>ne peut pas varier instantanément</b>.</p><p><b>Constante de temps</b> τ = R·C. Charge : u<sub>C</sub>(t) = E·(1 − e<sup>−t/τ</sup>) ; décharge : u<sub>C</sub>(t) = E·e<sup>−t/τ</sup>.</p><p>À t = τ : 63 % de la valeur finale (charge) ou 37 % de la valeur initiale (décharge). Le régime est considéré établi après <b>5 τ</b> (99,3 %).</p><p>Sur l\'oscilloscope : repérer 0,63·E et lire le temps correspondant = τ. Ordre de grandeur : 10 kΩ × 100 nF = 1 ms.</p>' }];
  C.signaux = [{ t: 'Signaux périodiques et oscilloscope', h: '<p><b>Période</b> T (s) et <b>fréquence</b> f = 1/T (Hz). Pour un sinus : <b>V<sub>eff</sub> = V<sub>max</sub>/√2</b> (≈ 0,707·V<sub>max</sub>) ; V<sub>pp</sub> = 2·V<sub>max</sub> (sans composante continue). Valeur moyenne d\'un sinus pur : 0 V.</p><p>Le multimètre en V∿ donne la valeur <b>efficace</b>, en V⎓ la valeur <b>moyenne</b>.</p><p>Oscilloscope : la <b>sensibilité verticale</b> (V/div) et la <b>base de temps</b> (s/div) se règlent pour occuper l\'écran ; le <b>déclenchement</b> (trigger, niveau et front) stabilise l\'image. Mesure = nombre de divisions × calibre. Couplage DC : tout le signal ; AC : la composante continue est retirée. La masse de la sonde est <b>reliée à la masse du circuit</b>.</p>' }];
  C.filtre = [{ t: 'Filtre RC passe-bas', h: '<p>Le condensateur laisse mal passer les basses fréquences et court-circuite les hautes : le montage R en série, C en parallèle sur la sortie est un <b>passe-bas</b>.</p><p>Fréquence de coupure : <b>f<sub>c</sub> = 1/(2π·R·C)</b>. Gain : G = U<sub>s</sub>/U<sub>e</sub>. À f<sub>c</sub>, G = 1/√2 ≈ <b>0,707</b>, soit <b>−3 dB</b>, et la sortie est en retard de 45°.</p><p>Gain en décibels : G<sub>dB</sub> = 20·log(U<sub>s</sub>/U<sub>e</sub>). Au-delà de f<sub>c</sub>, le gain décroît de <b>−20 dB par décade</b>.</p><p>Exemple : R = 1,6 kΩ, C = 100 nF → f<sub>c</sub> ≈ 1 kHz.</p>' }];
  C.transfo = [{ t: 'Le transformateur', h: '<p>Deux enroulements (primaire / secondaire) couplés par un noyau magnétique : il ne fonctionne qu\'en <b>alternatif</b> et <b>isole galvaniquement</b> le secondaire du secteur.</p><p>Rapport de transformation : <b>m = U<sub>2</sub>/U<sub>1</sub> = N<sub>2</sub>/N<sub>1</sub></b>. Un 230 V / 12 V a m ≈ 0,052. Les valeurs sont des tensions <b>efficaces</b> : la tension crête secondaire est 12·√2 ≈ 17 V.</p><p>À vide la tension est un peu plus haute que la valeur nominale ; en charge elle baisse (résistance des enroulements). Puissance apparente S = U·I en <b>VA</b>.</p><p><b>Sécurité</b> : le primaire est au potentiel du secteur (230 V) — on ne mesure jamais à main nue.</p>' }];
  C.redress = [{ t: 'Redressement', h: '<p>Une diode idéale conduit si V<sub>A</sub> &gt; V<sub>K</sub> + V<sub>seuil</sub> (≈ 0,6–0,7 V pour le silicium), sinon elle est bloquée.</p><p><b>Simple alternance</b> : une diode, on garde une alternance sur deux. V<sub>moy</sub> ≈ V<sub>max</sub>/π.</p><p><b>Double alternance</b> (pont de 4 diodes) : deux diodes conduisent à chaque alternance (on perd 2 × V<sub>seuil</sub>) ; V<sub>moy</sub> ≈ 2·V<sub>max</sub>/π ≈ 0,64·V<sub>max</sub>, fréquence d\'ondulation = <b>2 × 50 Hz = 100 Hz</b>.</p><p>La tension reste « pulsée » : on la filtre ensuite avec un condensateur.</p>' }];
  C.filtrage = [{ t: 'Filtrage par condensateur', h: '<p>Le condensateur se charge au sommet de chaque arche puis se décharge dans la charge : la tension devient presque continue avec une <b>ondulation</b> ΔV.</p><p>Pour un redressement double alternance : <b>ΔV ≈ I/(2·f·C)</b> (f = 50 Hz) ; simple alternance : ΔV ≈ I/(f·C). Plus C et plus f sont grands, plus l\'ondulation est faible.</p><p>Dimensionnement : C ≥ I/(2·f·ΔV). Ex. 110 mA, ΔV = 1 V : C ≥ 1,1 mF → on prend 2200 µF. Choisir une <b>tension de service</b> supérieure à V<sub>max</sub> (marge ≥ 30 %), attention à la polarité des chimiques.</p><p>Un condensateur vieilli (séché) a une capacité plus faible et une résistance série élevée : l\'ondulation augmente.</p>' }];
  C.regul = [{ t: 'Régulation linéaire (78xx)', h: '<p>Le régulateur <b>7805</b> fournit 5 V stables tant que U<sub>e</sub> ≥ U<sub>s</sub> + <b>dropout</b> (≈ 2 V) : il faut donc au moins ≈ 7 V en entrée, et pas plus de 35 V.</p><p>Il se comporte comme une résistance variable en série avec la charge : la puissance perdue est <b>P = (U<sub>e</sub> − U<sub>s</sub>)·I</b>, transformée en chaleur (rendement η = U<sub>s</sub>/U<sub>e</sub>). Si P est grande → dissipateur thermique.</p><p>Condensateurs de découplage (≈ 330 nF en entrée, 100 nF en sortie) pour la stabilité. Le régulateur a une limitation de courant (≈ 1 A) et une protection thermique.</p>' }];
  C.test = [{ t: 'Tester un composant hors tension', h: '<p>Toujours <b>hors tension</b> et, si possible, composant déconnecté d\'au moins une borne (sinon on mesure le réseau).</p><p><b>Ohmmètre</b> : le multimètre injecte un petit courant et mesure la tension. Résistance : comparer à la valeur nominale ± tolérance (5 % : bandes or). Coupée → « OL » ; en court-circuit → ≈ 0 Ω.</p><p><b>Test diode</b> : sens passant → affiche V<sub>seuil</sub> (≈ 0,5–0,7 V) ; sens bloquant → « OL ». Les deux sens bas = diode en court-circuit ; les deux « OL » = coupée.</p><p><b>Continuité</b> : bip si R &lt; quelques dizaines d\'Ω (fusible, câble, piste).</p><p>Astuce : l\'outil <b>🔴 Pointes</b> permet de poser les pointes d\'un clic sur les bornes, comme en vrai.</p>' }];
  C.zener = [{ t: 'La diode Zener', h: '<p>Polarisée en <b>inverse</b>, une Zener conduit à partir de sa tension V<sub>Z</sub> (claquage non destructif) et maintient alors ≈ V<sub>Z</sub> à ses bornes, malgré les variations de courant. En direct, elle se comporte comme une diode normale.</p><p>Stabilisation : résistance série R<sub>S</sub> + Zener en parallèle sur la charge. <b>R<sub>S</sub> = (E − V<sub>Z</sub>)/(I<sub>Z</sub> + I<sub>charge</sub>)</b>.</p><p>Il faut I<sub>Z min</sub> pour rester dans la zone de Zener ; la Zener dissipe P<sub>Z</sub> = V<sub>Z</sub>·I<sub>Z</sub> (≤ P<sub>max</sub>, 0,5 W ou 1,3 W). Au pire : charge débranchée, tout le courant passe dans la Zener.</p>' }];
  C.transistor = [{ t: 'Transistor bipolaire en commutation', h: '<p>NPN : le petit courant de <b>base</b> I<sub>B</sub> commande le courant de <b>collecteur</b> I<sub>C</sub> : <b>I<sub>C</sub> = β·I<sub>B</sub></b> (β ≈ 100–300) tant qu\'il est en régime linéaire. V<sub>BE</sub> ≈ 0,7 V quand la base conduit.</p><p><b>Bloqué</b> : I<sub>B</sub> = 0 → I<sub>C</sub> ≈ 0, V<sub>CE</sub> ≈ V<sub>cc</sub> (interrupteur ouvert).<br><b>Saturé</b> : I<sub>B</sub> est assez grand pour que I<sub>C</sub> = (V<sub>cc</sub> − V<sub>CEsat</sub>)/R<sub>C</sub>, V<sub>CE</sub> ≈ 0,1–0,2 V (interrupteur fermé).</p><p>Pour saturer : <b>I<sub>B</sub> ≥ I<sub>C</sub>/β</b>, avec une marge (×2 à ×5). R<sub>B</sub> = (V<sub>commande</sub> − 0,7)/I<sub>B</sub>.</p>' }];
  C.relais = [{ t: 'Relais et charges inductives', h: '<p>Un <b>relais</b> commande un circuit de puissance (contacts COM / NO normalement ouvert / NC normalement fermé) à partir d\'un petit courant dans sa <b>bobine</b>, avec isolation galvanique.</p><p>Une bobine s\'oppose aux variations de courant : <b>u = −L·di/dt</b>. Quand le transistor coupe brutalement le courant, une <b>surtension</b> de plusieurs dizaines de volts apparaît, capable de détruire le transistor (claquage, avalanche).</p><p>Solution : <b>diode de roue libre</b> en inverse aux bornes de la bobine : elle offre au courant un chemin pour s\'éteindre, la tension est limitée à ≈ V<sub>cc</sub> + 0,7 V. Cathode côté +.</p>' }];
  C.inverseur = [{ t: 'L\'AOP en amplificateur inverseur', h: '<p>Un amplificateur opérationnel (AOP) amplifie la différence ε = V<sub>+</sub> − V<sub>−</sub>. Il est alimenté en <b>±12 V</b> (alimentation symétrique) et sa sortie ne peut pas dépasser ≈ les tensions d\'alimentation : c\'est la <b>saturation</b>.</p><p>Avec une <b>contre-réaction</b> (R<sub>f</sub> de la sortie vers l\'entrée −), l\'AOP est en régime linéaire : ε ≈ 0 et V<sub>−</sub> ≈ V<sub>+</sub> = 0 V (masse virtuelle). Le courant d\'entrée est nul.</p><p><b>Gain G = V<sub>s</sub>/V<sub>e</sub> = − R<sub>f</sub>/R<sub>1</sub></b> (signe − : sortie en opposition de phase). Dès que |G·V<sub>e</sub>| dépasse la tension de saturation, la sortie est écrêtée.</p>' }];
  C.cre = [{ t: 'Comparateur et capteur LDR', h: '<p>La <b>LDR</b> (photorésistance) a une résistance qui <b>diminue quand l\'éclairement augmente</b> (quelques centaines d\'Ω en plein jour, plusieurs MΩ dans le noir).</p><p>Placée dans un <b>pont diviseur</b>, elle donne une tension V<sub>mesure</sub> image de la lumière. Un AOP <b>sans contre-réaction</b> (comparateur) compare V<sub>+</sub> et V<sub>−</sub> : si V<sub>+</sub> &gt; V<sub>−</sub> la sortie vaut +V<sub>sat</sub>, sinon −V<sub>sat</sub>. Un potentiomètre règle le <b>seuil</b> de basculement.</p><p>La sortie du comparateur commande ensuite un transistor et un relais ou une LED (lampe qui s\'allume à la tombée de la nuit).</p>' }];
  const METH = { t: 'Méthode de dépannage', h: '<ol><li><b>Constater</b> le symptôme (que fait le système, que devrait-il faire ?) ;</li><li><b>Hypothèses</b> : quels blocs de la chaîne fonctionnelle peuvent l\'expliquer ?</li><li><b>Mesurer sous tension</b> en remontant de la sortie vers l\'entrée : on cherche le premier point où la tension est anormale (dichotomie) ;</li><li><b>Localiser</b> le bloc, puis, <b>hors tension</b>, tester les composants (ohmmètre, diode, continuité) ;</li><li><b>Chercher la cause</b> avant de remplacer (un fusible qui fond est le symptôme d\'un court-circuit) ;</li><li><b>Réparer</b> (composant identique) et <b>contrôler</b> le fonctionnement complet.</li></ol><p><b>Sécurité</b> : couper et décharger les condensateurs avant d\'intervenir ; ne jamais court-circuiter ni mettre de fusible plus fort.</p>' };
  C.dep1 = [METH, { t: 'Rappels : la chaîne d\'alimentation 5 V', h: '<p>Secteur 230 V → <b>fusible</b> (protège du court-circuit, I²t) → <b>transformateur</b> (230 V → 12 V~, isolation) → <b>pont de diodes</b> (redressement) → <b>condensateur de filtrage</b> (≈ 16–17 V avec ondulation) → <b>régulateur 7805</b> (5 V) → charge.</p><p>Valeurs attendues : secondaire ≈ 12 V<sub>eff</sub> ; après filtrage ≈ 15–16 V ; sortie 5 V. Ondulation à 100 Hz. Les écarts guident la localisation : pas de tension du tout → fusible, transformateur ; tension filtrée OK mais pas de 5 V → régulateur ; forte ondulation → diode ouverte ou C séché.</p><p>Un composant en court-circuit peut en détruire d\'autres (panne <b>en cascade</b>) : toujours chercher la cause avant de remettre sous tension. La <b>caméra thermique</b> repère les composants anormalement chauds.</p>' }];
  C.dep2 = [METH, { t: 'Rappels : le transistor en commutation', h: '<p>Chaîne : SW1 → R<sub>B</sub> → base ; R<sub>C</sub> et LED en série avec collecteur-émetteur. Fonctionnement normal fermé : V<sub>BE</sub> ≈ 0,7 V, V<sub>CE</sub> ≈ 0,1 V (saturé), LED allumée. Ouvert : V<sub>BE</sub> ≈ 0, V<sub>CE</sub> ≈ V<sub>cc</sub>.</p><p>Diagnostic : V<sub>BE</sub> = 0 alors que SW1 est fermé → circuit de commande coupé (R<sub>B</sub>, fil, interrupteur). V<sub>BE</sub> ≈ 0,7 V mais V<sub>CE</sub> ≈ V<sub>cc</sub> → transistor coupé entre C et E. V<sub>CE</sub> ≈ 0 LED éteinte alors que SW1 ouvert → C-E en court-circuit.</p>' }];
  C.dep3 = [METH, { t: 'Rappels : l\'AOP inverseur et son alimentation', h: '<p>Un AOP a besoin de <b>V+ et V− (±12 V)</b> sur ses broches d\'alimentation : <b>vérifier l\'alimentation avant tout</b>. Sans une des deux, la sortie reste à 0 V ou bloquée.</p><p>Gain attendu G = −R<sub>f</sub>/R<sub>1</sub>. Sortie écrêtée à ≈ ±V<sub>sat</sub> quelle que soit l\'entrée → boucle de contre-réaction ouverte (R<sub>f</sub> coupée). Sortie à 0 V avec une entrée présente → R<sub>1</sub> coupée, AOP HS ou alimentation absente.</p><p>On compare à l\'oscilloscope entrée (CH1) et sortie (CH2).</p>' }];
  NS.coursFor = id => C[id] || [];
})(typeof window !== 'undefined' ? window : globalThis);
