/* coverage.js — matrice de couverture indicative du référentiel Bac Pro CIEL (électronique) */
(function (g) {
'use strict';
const NS = g.NS;
NS.COVERAGE = {
  note: 'Cette correspondance a été établie à partir de la connaissance générale du programme d\'électronique du Bac Pro CIEL (Cybersécurité, Informatique et réseaux, Électronique et Communication). Elle doit être validée et complétée par rapport au référentiel officiel en vigueur (ex. sosreferentiel.fr) avant usage en classe.',
  items: [
    ['Grandeurs électriques', 'Tension, courant, résistance, loi d\'Ohm', 'ok', 'ohm'],
    ['Grandeurs électriques', 'Puissance et énergie, échauffement, puissance max. d\'une résistance', 'ok', 'puissance'],
    ['Lois fondamentales', 'Associations série / parallèle', 'ok', 'assoc'],
    ['Lois fondamentales', 'Lois de Kirchhoff (nœuds, mailles)', 'ok', 'kirchhoff'],
    ['Lois fondamentales', 'Diviseur de tension / de courant', 'ok', 'diviseur'],
    ['Signaux', 'Signaux périodiques : période, fréquence, valeur moyenne, valeur efficace', 'ok', 'signaux'],
    ['Signaux', 'Régime transitoire RC, constante de temps', 'ok', 'rc'],
    ['Signaux', 'Filtre passif, fréquence de coupure', 'ok', 'filtre'],
    ['Mesure', 'Multimètre, oscilloscope, alimentation de laboratoire, GBF', 'ok', 'tous'],
    ['Mesure', 'Lecture d\'un signal à l\'oscilloscope : réglages, T, f, Umax, Upp, Umoy, Ueff, rapport cyclique, déphasage, couplage AC/DC', 'ok', 'osc_lect, osc_carre, osc_phi, osc_ac'],
    ['Composants', 'Diode, LED, résistance de limitation', 'ok', 'led'],
    ['Composants', 'Test de composants hors tension (ohmmètre, diode, continuité)', 'ok', 'test'],
    ['Composants', 'Diode Zener, stabilisation', 'ok', 'zener'],
    ['Composants', 'Transistor bipolaire en commutation', 'ok', 'transistor'],
    ['Composants', 'Relais, charge inductive, diode de roue libre', 'ok', 'relais'],
    ['Énergie', 'Transformateur monophasé', 'ok', 'transfo'],
    ['Énergie', 'Redressement mono / double alternance', 'ok', 'redress'],
    ['Énergie', 'Filtrage capacitif, ondulation', 'ok', 'filtrage'],
    ['Énergie', 'Régulation linéaire 78xx, dissipation thermique', 'ok', 'regul'],
    ['Amplification', 'AOP en régime linéaire (inverseur), saturation', 'ok', 'inverseur'],
    ['Amplification', 'AOP en comparateur, capteur LDR', 'ok', 'cre'],
    ['Maintenance', 'Dépannage d\'une alimentation (méthode, mesures, remplacement, contrôle)', 'ok', 'dep1'],
    ['Maintenance', 'Dépannage d\'une platine transistor / d\'un montage à AOP', 'ok', 'dep2, dep3'],
    ['Sécurité', 'Risque électrique, fusibles, protection (consignes dans les TP secteur)', 'part', 'transfo, dep1'],
    ['Capteurs / Chaînes', 'Conditionnement de capteurs (CTN, LDR)', 'part', 'cre'],
    ['Numérique', 'Logique combinatoire : portes, tables de vérité, familles CMOS / TTL', 'ok', 'portes'],
    ['Numérique', 'Logique séquentielle : bascule D, diviseur de fréquence, compteur binaire, compteur modulo N', 'ok', 'bascule, compteur, modulo'],
    ['Numérique', 'Microcontrôleur', 'no', 'à venir'],
    ['Composants', 'Temporisateur NE555 (astable), calcul de fréquence', 'ok', 'ne555'],
    ['Composants', 'Optocoupleur, isolation galvanique', 'ok', 'opto'],
    ['Composants', 'MOSFET de puissance en commutation, interface logique / puissance', 'ok', 'mosfet'],
    ['Maintenance', 'Dépannage d\'une platine logique', 'ok', 'dep_log'],
    ['Communication', 'Liaison série UART / RS-232 : trame, débit, parité, niveaux', 'ok', 'uart'],
    ['Communication', 'Bus de terrain Modbus RTU / RS-485 différentiel, CRC', 'ok', 'modbus'],
    ['Communication', 'Bus I²C et SPI (adresse, ACK, modes)', 'ok', 'i2c, spi'],
    ['Communication', 'Modulation, transmission radio, réseaux Ethernet (couches physiques)', 'no', 'à venir'],
    ['Énergie', 'Alimentation à découpage, onduleur', 'no', 'à venir'],
    ['Amplification', 'Montage non inverseur, sommateur, intégrateur, trigger de Schmitt', 'no', 'à venir'],
  ],
  limits: [
    'Le moteur simule des circuits mono-phasés ; la logique numérique est comportementale (portes, 555, bascule, compteur), sans microcontrôleur ni CPLD.',
    'Les analyseurs de trames et générateurs de protocoles (UART, Modbus, I²C, SPI) sont des modèles idéalisés : pas de câblage de bus réel (terminaisons, longueurs, rebonds).',
    'Les modèles de composants (diodes, transistors, AOP, régulateurs) sont des modèles simplifiés réalistes, pas des modèles SPICE constructeur.',
    'Le temps simulé peut être plus lent que le temps réel pour des signaux de fréquence élevée (≥ 10 kHz).',
    'Les pannes sont injectées de manière déterministe (variantes numérotées) : le mode enseignant révèle la panne.',
  ],
};
})(typeof window !== 'undefined' ? window : globalThis);
